[package]
name = "budget-common"
version = "0.1.0"
edition = "2021"


[dependencies]
uuid = { version = "1.3.3", features = ["rand", "v4", "serde"] }
serde = { version = "1.0.163", features = ["derive"] }